// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeQ5Dxp4OQZZDMIwwH_k5gU6j-_NT_1QM',
    appId: '1:547628885478:web:d5dba17372a10e4a98e227',
    messagingSenderId: '547628885478',
    projectId: 'capstone-login-c29fb',
    authDomain: 'capstone-login-c29fb.firebaseapp.com',
    storageBucket: 'capstone-login-c29fb.firebasestorage.app',
    measurementId: 'G-CVQGTW1435',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdh4Rx8EaA0AI5ybpo6UU98hTwPLGDMzs',
    appId: '1:547628885478:android:b13f6241d990405498e227',
    messagingSenderId: '547628885478',
    projectId: 'capstone-login-c29fb',
    storageBucket: 'capstone-login-c29fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOgX1evL5Iop-qLXVK41122WkLDQaflis',
    appId: '1:547628885478:ios:2ade2207b1ccb23d98e227',
    messagingSenderId: '547628885478',
    projectId: 'capstone-login-c29fb',
    storageBucket: 'capstone-login-c29fb.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOgX1evL5Iop-qLXVK41122WkLDQaflis',
    appId: '1:547628885478:ios:2ade2207b1ccb23d98e227',
    messagingSenderId: '547628885478',
    projectId: 'capstone-login-c29fb',
    storageBucket: 'capstone-login-c29fb.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeQ5Dxp4OQZZDMIwwH_k5gU6j-_NT_1QM',
    appId: '1:547628885478:web:3cd185fed8e52a6598e227',
    messagingSenderId: '547628885478',
    projectId: 'capstone-login-c29fb',
    authDomain: 'capstone-login-c29fb.firebaseapp.com',
    storageBucket: 'capstone-login-c29fb.firebasestorage.app',
    measurementId: 'G-RT3YJ3JYB4',
  );
}
